#!/bin/bash
#by MP mackendy-pierre Anselin

if [ -e Makefile ]  && [ ! -e libasm.so ]
    then
    make fclean
    make re
fi

if [ ! -e libasm.so ]
    then
    echo "Error : The minilibc_tester must be in same repository than libam.so file"
    exit 84
fi

if ()