#!/bin/bash
#by MP mackendy-pierre Anselin
if [ -e .my_asm_minilibc.test ]
  then
    rm ./.my_asm_minilibc.test
elif [ -e .asm_minilibc.test ];
  then
    rm ./.asm_minilibc.test
elif [ -e minilibc.h ]
  then
    rm ./minilibc.h
fi


if [ ! -e .main.test_asm.c ]
   then
       curl http://xf.iksaif.net/epitech/.rendu/asm/minilibc/main.c > .main.test_asm.c
fi
if [ ! -e minilibc.h ];
  then
      curl http://xf.iksaif.net/epitech/.rendu/asm/minilibc/minilibc.h > minilibc.h
fi

gcc .main.test_asm.c

LD_PRELOAD=`pwd`/libasm.so ./a.out > .my_asm_minilibc.test
./a.out > .asm_minilibc.test

diff -a .my_asm_minilibc.test .asm_minilibc.test
ret=$?
if [ $ret == 0 ]
then
    echo -e "\033[32m OK\033[00m";
else
    echo -e "\033[31m KO\033[00m";
fi

rm ./.main.test_asm.c
rm ./minilibc.h
rm a.out

exit $ret
